### ISSUE TITLE
与Galactifun 星际科技的冲突

### ISSUE THREAD

**Issue by huazhongyouji** [GuizhanCraft/FoxyMachines-CN#12]

**Comment by ybw0014** [comment]
请先提供相关插件的启用时日志

**Comment by huazhongyouji** [comment]
> ### 检查项目
> * [x]  你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
> * [ ]  你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
> * [ ]  你没有对下载的文件内容进行任何更改
> * [x]  你没有安装`CS-CoreLib`
> * [x]  你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题
> 
> ### 问题描述
> 无法与Galactifun 星际科技插件一起用，有冲突。放一起打开服务器只会出现星际科技的插件。
> 
> ### 复现步骤
> 将FoxyMachines-Build 14 zh-CN(ybw0014) (git [cf4ceb4](https://github.com/SlimefunGuguProject/FoxyMachines/commit/cf4ceb4b7b6e05e1b9a31abdad1e07c3c80b51da))和Galactifun-Build 14 zh-CN(baoad) (git 5da28f5)放入plugins内。
> 
> ### 预期行为
> Galactifun 星际科技与FoxyMachines 神秘科技插件会冲突
> 
> ### 服务器日志
> _No response_
> 
> ### 错误报告
> _No response_
> 
> ### 服务端软件
> Paper
> 
> ### Minecraft 版本
> 1.18.x
> 
> ### CS-CoreLib 版本
> * [x]  我没有安装CS-CoreLib
> 
> ### Slimefun版本
> Slimefun-v4.9-release-2022.03.2
> 
> ### 插件版本
> 14
