### ISSUE TITLE
区块加载器数据紊乱

### ISSUE THREAD

**Issue by yyhhkya** [GuizhanCraft/FoxyMachines-CN#15]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题

### 问题描述

区块内没有加载器 但区块已处于强制加载状态
![image](https://user-images.githubusercontent.com/87574541/199671179-6a5dd061-4a67-4eac-a6dd-64c0cb185bab.png)

### 复现步骤

诱因是“[高级信标]BeaconPlus”插件

关闭“[高级信标]BeaconPlus”插件配置文件的放置权限后，玩家放不出来，但粘液科技以为已经放置出来了，从而造成区块强制加载。

### 预期行为

无

### 服务端软件

Paper

### Minecraft 版本

1.16.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://user-images.githubusercontent.com/87574541/199671318-62aecb5a-72be-4ee6-a038-8a9096a1df7f.png)

### 插件版本

16

**Comment by yyhhkya** [comment]
我已经卸载了“BeaconPlus”，但并没有恢复，我需要恢复区块成非强制加载的方法

**Comment by ybw0014** [comment]
由于BeaconPlus为付费插件，因此我无法复现问题。
可能BeaconPlus在Slimefun之后取消了放置，所以这是一个幽灵方块问题。你可以查阅[wiki](https://slimefun-wiki.guizhanss.cn/Common-Issues?id=unplaceable-blocks)中的"常见问题-幽灵方块"部分，使用调试鱼来移除方块信息。

**Comment by yyhhkya** [comment]
我已经试过用调试鱼来清除方块信息了 可是没有用

**Comment by yyhhkya** [comment]
请问强制加载的区块是记录在哪里的

**Comment by ybw0014** [comment]
区块信息记录于地图目录中，我不清楚有哪些插件可以直接取消区块的强制加载

**Comment by yyhhkya** [comment]
那我现在该怎么办呢 怎样才能恢复

**Comment by yyhhkya** [comment]
那个玩家拥有加载器的数量是记录在哪的
