### ISSUE TITLE
区块加载器拆除后区块仍处于强加载状态

### ISSUE THREAD

**Issue by GZXSSS** [GuizhanCraft/FoxyMachines-CN#23]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题

### 问题描述

我不清楚这是否为BUG,但是拆除后区块仍处于强加载状态。

![224405nqmuoxko9wsuwnzk](https://github.com/SlimefunGuguProject/FoxyMachines/assets/72150787/4ac3daaf-87b1-4c6c-98cc-f4421aa9fb18)
![224358ecssxcgcx1z1cx9m](https://github.com/SlimefunGuguProject/FoxyMachines/assets/72150787/2c3197ff-c9c4-4e04-81ca-604a8c50c351)
![224410gmx22li8mzyt3ld2](https://github.com/SlimefunGuguProject/FoxyMachines/assets/72150787/657a2e40-8c46-4773-8b75-1a62b1f10a26)

### 复现步骤

1.放置区块加载器
2.拆除区块加载器

### 预期行为

再次放置提示区块已经为常加载

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

[22:08:14 INFO]: Slimefun 运行的服务器环境:
Paper git-Paper-550 (MC: 1.19.4)
Slimefun 23.07.22-release
Metrics-组件 #29
Java 17

由 StarWishsama 汉化
请不要将此版本信息截图到 Discord/Github 反馈 Bug
优先到汉化页面反馈

安装的附属插件: (15)
  GuizhanLibPlugin vBuild 31 (git f6aa398)
  FoxyMachines vBuild 23 (git 8e6a87b)
  Residence v5.1.1.2
  DynaTech vBuild 49 zh-CN(ybw0014) (git 7d687ba)
  ExoticGarden vBuild 15 zh-CN(ybw0014) (git 1aa87ca)
  DankTech2 vBuild 5 zh-CN(ybw0014) (git e948f39)
  InfinityExpansion vBuild 10 (git 15accb8)
  Supreme vBuild 15 zh-CN(SlimefunGuguProject) (git 50ee209)
  SlimeGlue v1.0.2-b262a4a
  SlimeCustomizer vBuild 26 zh-CN(SlimefunGuguProject) (git 5115d68)
  LiteXpansion vBuild 26 (git 6efc2c9)
  SFCalc vBuild 4 zh-CN(ybw0014) (git ca78ab1)
  Galactifun vBuild 18 zh-CN(baoad) (git 4c9d4f9)
  TranscEndence vBuild 6 zh-CN(baoad) (git 12c5713)
  FluffyMachines vBuild 24 (git 0b5b542)

### 插件版本

Build 23 (git 8e6a87b)

**Comment by GZXSSS** [comment]
后台无报错

**Comment by ybw0014** [comment]
确实是bug，但我不清楚怎么修

**Comment by ybw0014** [comment]
已在新版本中修复。如果挖掉时没有变成玻璃，那么这个方块已经不是区块加载器了，也就无法取消强制加载。

**Comment by GZXSSS** [comment]
补充一点，如果已经放置区块加载器，可以使用
forceload query 查找强加载区块
然后使用
forceload remove
移除强加载区块
这样就可以完美解决之前放置过区块加载器但是无法取消的问题。
