### ISSUE TITLE
挖除区块加载器后不返还区块加载器放置名额

### ISSUE THREAD

**Issue by LangZongz** [GuizhanCraft/FoxyMachines-CN#25]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题

### 问题描述

拆除区块加载器后区块确实停止强加载，但玩家可继续放置的区块加载器名额不变。

### 复现步骤

1.放满8个区块加载器（假设服务器设置的“每位玩家可以摆放的区块加载器上限”为8）
2.挖除一个区块加载器，并观察到正常地留下一个玻璃
3.再次试图放置区块加载器

### 预期行为

/forceload query查询到区块停止强制加载，但再次试图放置区块加载器时提示“已达到区块加载器最大数量限制”
![image](https://github.com/SlimefunGuguProject/FoxyMachines/assets/129711891/28b0a9c8-6234-4ab9-ab7d-13291cd31b04)

### 服务器日志

后台无报错

### 错误报告

后台无报错

### 服务端软件

Purpur

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun 运行的服务器环境:
Purpur git-Purpur-2062 (MC: 1.20.1)
Slimefun 23.07.22-release
Metrics-组件 #29
Java 17
由 StarWishsama 汉化
请不要将此版本信息截图到 Discord/Github 反馈 Bug
优先到汉化页面反馈

安装的附属插件: (28)
 GuizhanLibPlugin vBuild 35 (git 11baf1f)
 FoxyMachines vBuild 25 (git a980fda)
 FNAmplifications vBuild 5 (git cd80aab)
 DynaTech vBuild 52 (git 3e5f76f)
 SimpleMaterialGenerators vBuild 5 zh-CN(SlimefunGuguProject) (git e05d257)
 InfinityExpansion vBuild 11 (git f9fe427)
 Supreme vBuild 15 zh-CN(SlimefunGuguProject) (git 50ee209)
 GuizhanCraft vBuild 12 (git 1ced47e)
 ElectricSpawners vBuild 5 (git 6fa0de2)
 SlimyTreeTaps vBuild 2 zh-CN(ybw0014) (git 8a58b9f)
 MobCapturer vBuild 14 (git 17950ca)
 SlimeTinker vBuild 47 (git 2575d37)
 Galactifun vBuild 18 zh-CN(baoad) (git 4c9d4f9)
 TranscEndence vBuild 6 zh-CN(baoad) (git 12c5713)
 GeneticChickengineering vBuild 8 (git a6cd374)
 FluffyMachines vBuild 25 (git 9bca1f2)
 Gastronomicon vBuild 7 (git 38ba535)  
 SlimefunWarfare vBuild 9 zh-CN(ybw0014) (git 91bf6cf)
 Residence v5.1.3.0
 ExoticGarden vBuild 17 (git 2a33c6d) 
 FinalTECH vBuild 28 zh-CN(ECRO) (git f7d3a03)
 SlimeGlue v1.0.2-04c4247
 SlimeCustomizer vBuild 26 zh-CN(SlimefunGuguProject) (git 5115d68)
 LiteXpansion vBuild 29 (git 546275f)
 OreGeneration v1.0
 SlimeHUDPlus v1.2.7
 SoulJars vBuild 9 (git f13e461)
 Networks-Changed v1.2.0

### 插件版本

25

**Comment by ybw0014** [comment]
这是丢失了放置玩家的信息，导致没有恢复。
我可以考虑加一个指令可以让管理员手动设置玩家当前的上限。

**Comment by LangZongz** [comment]
好的，能否修复丢失玩家信息的问题呢？

**Comment by ybw0014** [comment]
放置玩家信息丢失的原因未知，暂时不考虑修复。
