### ISSUE TITLE
无头骑士的坐骑会将无头骑士甩下

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [GuizhanCraft/FoxyMachines-CN#27]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题

### 问题描述

召唤无头骑士后，它的骷髅马会在数秒内将无头骑士甩下马。

### 复现步骤

1. 使用 `/sf give` 指令获得一个无头骑士刷怪蛋；
2. 使用刷怪蛋，召唤无头骑士；
3. 等待一段时间，无头骑士会被坐骑甩下马。

### 预期行为

无头骑士的坐骑不会主动将无头骑士甩下。

### 服务端软件

Spigot

### Minecraft 版本

本插件不支持旧版本

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://github.com/SlimefunGuguProject/FoxyMachines/assets/86547296/dd260c8c-742b-45b1-97f3-e6ce6305b79c)

### 插件版本

27

**Comment by Violet-Nonbloosom** [comment]
另外，Issue 模板中的`Minecraft版本`一栏中没有较新的版本，所以我留空了。

**Comment by ybw0014** [comment]
有没有其他插件

**Comment by Violet-Nonbloosom** [comment]
> 有没有其他插件

只有 SkinRestorer，而且把它去掉后依然有这个问题。

**Comment by Violet-Nonbloosom** [comment]
试了一下，把骷髅马设为驯化之后，问题解决了。
