### ISSUE TITLE
【神秘科技】幽灵方块非法转实

### ISSUE THREAD

**Issue by JiangQiYan713** [GuizhanCraft/FoxyMachines-CN#5]
## Description (Required)

Using the fishing rod can change the motion state of the ghost block entity (falling block), 
make it collide with the real block and turn it into reality, 
then it can be destroyed by the player.
利用鱼竿可以改变幽灵方块实体（下落的方块）的运动状态，
使其与真实方块碰撞导致转实，
从而可以被玩家破坏。

## Steps to reproduce the Issue (Required)

(sorry, I can't send video,but reproducing this bug is very simple.)
1.Right click the ghost square with the fishing rod
2.Stay away from the hook for a distance and right-click to fish back
3.Then u can see the ghost block moving in the air or landing as a real block :)
（抱歉，我无法发送视频，但复制此错误非常简单。）
1.用鱼竿右击幽灵方块
2.远离鱼钩一段距离，然后右键单击以向后钓鱼
3.然后你可以看到幽灵块在空中移动或着陆成为真实方块 :)

## Expected behavior (Required)

Fishing rods also cannot interact with ghost block.
钓鱼竿也无法对幽灵方块进行交互。

## Server Log / Error Report

There are no errors reported.

## Environment (Required)

![ver](https://user-images.githubusercontent.com/91627081/155832188-92e29583-6134-4b72-8b9b-3cc866a62376.png)

 - Minecraft Version: git-Paper-214 (MC: 1.18.1)
 - CS-CoreLib Version: ?
 - Slimefun Version: 4.9-test-cargo_stacking_items-ff32a4a
 - Plugin Version: ?

**Comment by ybw0014** [comment]
https://github.com/GallowsDove/FoxyMachines/pull/52

**Comment by JiangQiYan713** [comment]
这边建议修复不要只针对钓鱼竿，任何能够改变幽灵方块动量数据的方法都应该被阻止

**Comment by ybw0014** [comment]
> 这边建议修复不要只针对钓鱼竿，任何能够改变幽灵方块动量数据的方法都应该被阻止

其他的需要再研究下
