### ISSUE TITLE
【神秘科技】幽灵方块可转实2

### ISSUE THREAD

**Issue by JiangQiYan713** [GuizhanCraft/FoxyMachines-CN#6]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FoxyMachines/issues)，且没有找到相同的问题

### 问题描述

Using various explosive and shocks
Landing it leads to reallocation,
Then it can be destroyed by players.
利用各种爆炸冲击
使其着陆导致转实，
从而可以被玩家破坏。

### 复现步骤

Find a way to use coolie fear, withering spirit, fireball, evil soul fireball, the head of withering spirit, the explosion of end Shadow crystal or the shock wave of end shadow dragon to give any ghost square a momentum downward towards the ground, and the ghost square can become the original square when it contacts the ground..
想办法利用苦力怕、凋灵、火球、恶魂火球、凋灵之首、末影水晶的爆炸或末影龙的冲击波，给予任意幽灵方块一个向下朝向地面的动量，幽灵方块接触地面即可变成原版方块。

Uploading 1650642103672.mp4…

### 预期行为

Stop the momentum change of the ghost square.
阻止幽灵方块的动量改变。

### 服务器日志

There are no errors reported.

### 错误报告

There are no errors reported.

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun 2022.04-release

![FCO$F@%$0Q52 45WXUXE(G](https://user-images.githubusercontent.com/91627081/164752381-d7c81da1-4285-4825-a5d6-d743fbb69a89.png)
![@U`J$A8C885UY1}6C )BD2J](https://user-images.githubusercontent.com/91627081/164752489-8399ce77-8110-4d1b-86eb-b87d87e3e0a5.png)

### 插件版本

10

**Comment by ybw0014** [comment]
机翻不如不加，不过这确实是个问题

**Comment by JiangQiYan713** [comment]
焯 才发现苦力怕翻错了（

**Comment by ybw0014** [comment]
由于paper的API并没有提供与爆炸影响实体相关的事件，这种情况无法处理。
